## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [3]:
import numpy as np

x1 = np.arange(5,11)
x2 = np.arange(15,21)

# outer product
p_out = [] 

assert (len(x1)==len(x2)), 'Lists must be the same length!'

for i in range(len(x1)): 
    row = [] 
    for j in range(len(x2)):
        row.append(x1[i]*x2[j])
        
    p_out.append(row)

#print outer product
print('Outer Product:',p_out) 

Outer Product: [[75, 80, 85, 90, 95, 100], [90, 96, 102, 108, 114, 120], [105, 112, 119, 126, 133, 140], [120, 128, 136, 144, 152, 160], [135, 144, 153, 162, 171, 180], [150, 160, 170, 180, 190, 200]]


In [12]:
#Trace 
trace = np.zeros(1)

for i in range(len(x1)):
    trace = trace + p_out[i][i]

print('The trace is:', trace)

#numpy
n_out = np.outer(x1,x2)
print('Outer Product:', n_out)

n_trace = np.trace(n_out)
print('The trace is:', n_trace)

The trace is: [805.]
Outer Product: [[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]
The trace is: 805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [24]:
#Make two matrices of random numbers

A = np.random.random((4, 3))
B = np.random.random((3, 4))


print(A)
print(B)

#Make a for loop
C = []

for i in range(A.shape[0]):
    row = []
    for j in range(B.shape[1]):
        row.append(sum(A[i,:]*B[:,j]))
    
    C.append(row)
    
C = np.asmatrix(C)
print(C)



[[0.73809987 0.23464271 0.80796134 0.45313709]
 [0.59955339 0.19460578 0.68960816 0.36911045]
 [0.21894584 0.22103265 0.20057479 0.37710513]
 [0.75442554 0.15373149 0.80115104 0.33253449]]


In [25]:
C = A.dot(B)
print(C)

[[0.73809987 0.23464271 0.80796134 0.45313709]
 [0.59955339 0.19460578 0.68960816 0.36911045]
 [0.21894584 0.22103265 0.20057479 0.37710513]
 [0.75442554 0.15373149 0.80115104 0.33253449]]


In [34]:
C = [[sum(A[i,:]*B[:,j]) for j in range(B.shape[1])] for i in range(A.shape[0])]
C

[[0.738099866814304,
  0.23464270849584723,
  0.8079613396191465,
  0.45313708571324457],
 [0.5995533910094223,
  0.19460578381873292,
  0.6896081632652964,
  0.36911045453128116],
 [0.21894583751637456,
  0.22103265030654962,
  0.2005747906838815,
  0.3771051300815928],
 [0.7544255384402573,
  0.15373148705249218,
  0.8011510357358734,
  0.33253449248847866]]

In [31]:
#numpy
c = np.dot(A,B)
print(c)

[[0.73809987 0.23464271 0.80796134 0.45313709]
 [0.59955339 0.19460578 0.68960816 0.36911045]
 [0.21894584 0.22103265 0.20057479 0.37710513]
 [0.75442554 0.15373149 0.80115104 0.33253449]]


In [32]:
#fancy indenx
row = np.array([0, 1]) 
col = np.array([0, 1])

print(c[row[:, np.newaxis], col])

[[0.73809987 0.23464271]
 [0.59955339 0.19460578]]
