In [5]:
# import numpy
import numpy as np

In [2]:
# create a 1d array
x = np.linspace(0,9,10)

x[1]                     # just the second entry, remember 0 based indexing

# specific start and stop points (exclusive)
x[0:2]                   # the first and second entries in the array, so N>=0 and N<2 (note the < upper bound - not inclusive)

# assign the 2nd - 4th element to 100 (index 1,2,3)
x[1:4] = 100               
print(x[1:4])

# start, stop, step interval
print(x[0:8:2])

# reverse x
print(x[::-1])

# iterate over all elements in x
for i in x:
    print(i*3)    # then i takes the value of each element in x

[100. 100. 100.]
[  0. 100.   4.   6.]
[  9.   8.   7.   6.   5.   4. 100. 100. 100.   0.]
0.0
300.0
300.0
300.0
12.0
15.0
18.0
21.0
24.0
27.0


## multidimentional array indexing, slicing etc

In [3]:
x = np.round(np.random.rand(10,5)*10)   # generate a matrix of uniformly distributed random numbers over 0:10
print(x)

x[0,0]     # first row, first column
x[2,3]     # third row, 4th column

x[:, 3]    # all entries in the 4th column 
x[3, :]    # all entries in the 4th row
x[0:2, 4]  # first two entries of the 5th column
x[6, 2:4]  # 7th row, 3rd and 4th entries. 

x[6]       # if not all dims specified then missing values are considered complete slices
x[6,]      # these three ways of writing all do the same thing...
x[6,:]

# tricks...
print('last row: ', x[-1,:])     # last row
print('last column: ', x[:,-1])  # last column
print('last entry: ', x[-1,-1])  # last value

# iterating goes over the first dim (rows)
for r in x:
     print(r)
        
# can also iterate over all entries in the array using 'flat'
# will proceed along 1st row, then to 2nd row, etc. across the rows
for a in x.flat:
    print(a)

[[ 3.  7.  3.  2.  2.]
 [ 6. 10.  5.  7.  4.]
 [ 1.  3.  0.  7.  2.]
 [ 4.  2.  5.  8.  5.]
 [ 6.  8. 10.  7.  2.]
 [ 3.  6.  8.  6.  5.]
 [ 4. 10.  9.  2.  0.]
 [ 1.  8.  5.  7.  1.]
 [ 1.  9.  1.  1.  8.]
 [ 1.  7.  3.  2.  7.]]
last row:  [1. 7. 3. 2. 7.]
last column:  [2. 4. 2. 5. 2. 5. 0. 1. 8. 7.]
last entry:  7.0
[3. 7. 3. 2. 2.]
[ 6. 10.  5.  7.  4.]
[1. 3. 0. 7. 2.]
[4. 2. 5. 8. 5.]
[ 6.  8. 10.  7.  2.]
[3. 6. 8. 6. 5.]
[ 4. 10.  9.  2.  0.]
[1. 8. 5. 7. 1.]
[1. 9. 1. 1. 8.]
[1. 7. 3. 2. 7.]
3.0
7.0
3.0
2.0
2.0
6.0
10.0
5.0
7.0
4.0
1.0
3.0
0.0
7.0
2.0
4.0
2.0
5.0
8.0
5.0
6.0
8.0
10.0
7.0
2.0
3.0
6.0
8.0
6.0
5.0
4.0
10.0
9.0
2.0
0.0
1.0
8.0
5.0
7.0
1.0
1.0
9.0
1.0
1.0
8.0
1.0
7.0
3.0
2.0
7.0


## pull out subset of rows and columns

In [6]:
# generate a matrix of random numbers over 0-1
x = np.random.rand(4,3) 
print(x)

# first two rows - note that you don't have to specify the 2nd dim - and note that 
# '2' here means rows 0 and 1 (not 0 through 2!) ":" = keep on going
y = x[:2] 
print('\n', y)

# can also take the last two rows...in the same manner...in this case rows 3 and 4
y = x[2:] 
print('\n', y)

# first two rows, 1st column
y = x[:2,0] 
print('\n', y)

# rows 3 - end, columns 2 - end
y = x[2:,1:]
print('\n', y)

[[0.04987503 0.96203202 0.87246869]
 [0.94888906 0.08278995 0.37821837]
 [0.53710968 0.21657187 0.92833328]
 [0.73308558 0.1982164  0.39520462]]

 [[0.04987503 0.96203202 0.87246869]
 [0.94888906 0.08278995 0.37821837]]

 [[0.53710968 0.21657187 0.92833328]
 [0.73308558 0.1982164  0.39520462]]

 [0.04987503 0.94888906]

 [[0.21657187 0.92833328]
 [0.1982164  0.39520462]]


<div class="alert alert-info">
important - slicing an array creates a view of it! if you change the view, you also will change the original data!
</div>

In [7]:
z = x[:,]
print(z.shape)
# change all values in z using [:]
z[:]=100     # so if you change data in z it will also change in x

print(x)

(4, 3)
[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


## Fancy indexing...using arrays to index arrays - used all the time in data analysis...

<div class="alert alert-info">
fancy indexing always makes a COPY of the data (unlike slicing which creates a view)!!!
</div>

In [10]:
# define an array
x = np.random.rand(3,4)

# index array - can be a tuple
y = (2,3)

# index
print(x)
print('\n x indexed at tuple y: ', x[y])

[[0.44870785 0.82877831 0.97137347 0.62337343]
 [0.41097055 0.63947809 0.63070452 0.3502278 ]
 [0.95046602 0.02381065 0.22683538 0.62103137]]

 x indexed at tuple y:  0.6210313689689914


In [14]:
# can use fancy indexing to extract elements in a particular order
print(x)

# this will extract the 3rd row, then the 2nd row, then the first row
x[[2,1,0]]

# and this will extract all rows from the 2nd, 3rd and then 1st column. 
x[:,[1,2,0]]

[[0.6547825  0.89001926 0.7174017  0.50216638]
 [0.9008124  0.50064607 0.98777879 0.75834632]
 [0.84218719 0.84806166 0.12696453 0.94835725]]


array([[0.89001926, 0.7174017 , 0.6547825 ],
       [0.50064607, 0.98777879, 0.9008124 ],
       [0.84806166, 0.12696453, 0.84218719]])

In [11]:
# or can pass in multiple arrays...will return a 1D array 
# corresponding to each set of tuples (1,1) and (2,2) in this case
print(x)
x[[1,2],[1,2]]

[[0.6547825  0.89001926 0.7174017  0.50216638]
 [0.9008124  0.50064607 0.98777879 0.75834632]
 [0.84218719 0.84806166 0.12696453 0.94835725]]


array([0.50064607, 0.12696453])

<div class="alert alert-info">
As opposed to selecting a set of tuples, you can also select a block of indices from a matrix. 
</div>

In [13]:
# grab the lower right chunk of data. 
print(x, '\n')
print(x[[1,2]][:,[2,3]])  # 2nd term here extracts all rows from columns, first arg says restrict to last two rows. 

[[0.6547825  0.89001926 0.7174017  0.50216638]
 [0.9008124  0.50064607 0.98777879 0.75834632]
 [0.84218719 0.84806166 0.12696453 0.94835725]] 

[[0.98777879 0.75834632]
 [0.12696453 0.94835725]]
